services:
  postgres:
    image: postgres:latest
    container_name: income_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: income_user
      POSTGRES_PASSWORD: income_password
      POSTGRES_DB: income_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
